language: go
go:
  - 1.6
before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - glide install
  - go test $(glide novendor)
  - goveralls -service=travis-ci
notifications:
  recipients:
    - i@yanyiwu.com
  email:
    on_success: change
    on_failure: always
